### ISSUE TITLE
Kattello Agent install fails because the repo isn't registered yet

### ISSUE THREAD

**Issue by TheLunaticScripter** [chef-partners/redhat-subscription-manager-cookbook#25]
### Issue

When registering a new node the katello-agent installs but it is not able to pull down the .rpm because the repo where has not been registered yet.

### Cookbook Code
```ruby
rhsm_register node['etp_oraunix_mgmt']['rhel_satellite_host'] do
  organization '<Organization>'
  activation_key 'rhel_7'
  satellite_host node['etp_oraunix_mgmt']['rhel_satellite_host']
end

rhsm_repo '\*-satellite-tools-\*-rpms' do
  action :enable
end
```

### Attempted Workarounds
I attempted to move the repo add above the registration and that failed because it didn't know where the repo is.

**Comment by donwlewis** [comment]
So another way around this would be to make sure the repo is is enabled with your activation key.  I generally disable the katello-agent install, and add that to my base cookbook for all utilities.
