### ISSUE TITLE
Expose "name" attribute for "--name" argument of subscription-manager

### ISSUE THREAD

**Issue by alancdavis01** [chef-partners/redhat-subscription-manager-cookbook#26]
RHSM includes the ability to set the hostname to be used for the registration by using the "--name" option. This feature isn't exposed in the cookbook attributes.

From subscription-manager help : 

 ` --name=SYSTEMNAME     name of the system to register, defaults to the hostname
`

This is useful during test-kitchen testing to ensure the hostname used is unique.

**Comment by alancdavis01** [comment]
On further testing, katello/foreman apparently ignore the 'name' for, at least, GUI display so getting this to work will involve code changes in those projects as well. Closing this issue as impractical at this time.

**Comment by donwlewis** [comment]
@alancdavis01 I started messing with this and was able to get it to work.  What version of satellite are you running?
