### ISSUE TITLE
Guard katello-agent install?

### ISSUE THREAD

**Issue by civik** [chef-partners/redhat-subscription-manager-cookbook#3]
This cookbook will fail if the RHEL 'common' repos aren't enabled by the activation key due to the register action attempting to install the 'katello-agent' package.  Ideally the Katello agent install could be a  boolean parameter of the rhsm_register provider.  Katello-agent isn't a 100% requirement so its install should be optional.

**Comment by adamleff** [comment]
For proper RH Satellite use, katello-agent is required and the cookbook just follows their install guide accordingly.  However, I can see that a user may not want it installed but still wish to use the cookbook to manage registrations, subscriptions, etc. I'll add the new property (defaulting to true) next week!

**Comment by adamleff** [comment]
PR #4 opened to add this functionality. Please follow that PR for updates. Once it's merged, I'll push up a new release to the Supermarket. Thanks!
