### ISSUE TITLE
Registration fails in non-English environments

### ISSUE THREAD

**Issue by kleini** [chef-partners/redhat-subscription-manager-cookbook#32]
Execution of RedHat subscription-manager commands is not agnostic regarding language settings

    [root@defaultrhel7-marcus-marcus-mqt0fg9 cloud-user]# subscription-manager status
    +-------------------------------------------+
       Systemstatusdetails
    +-------------------------------------------+
    Gesamtstatus: Unbekannt
    

and the cookbook fails to check the output status and believes the system is already registered.

**Comment by kleini** [comment]
[root@defaultrhel7-marcus-marcus-mqt0fg9 cloud-user]# export LANG=en_US.UTF-8
    [root@defaultrhel7-marcus-marcus-mqt0fg9 cloud-user]# subscription-manager status
    +-------------------------------------------+
       System Status Details
    +-------------------------------------------+
    Overall Status: Unknown
    

Will try to create a pull request and run the status check always with LANG=en_US.

**Comment by kleini** [comment]
Fixed with https://github.com/chef-partners/redhat-subscription-manager-cookbook/pull/33

**Comment by kleini** [comment]
I am using now

    ENV['LANG'] = 'en_US.UTF-8'

in my deployment wrapper cookbook. This solves the problem, too. Please decide whether my environment setting or the change on the cookbook makes more sense.

**Comment by jjasghar** [comment]
The fix is probably better. We don't support many non-US languages, so to force this is probably a good workaround for the time being.

I do have one comment on the PR though, please address that there.
