### ISSUE TITLE
rhsm_register fails if subscription-manager isn't installed

### ISSUE THREAD

**Issue by Stromweld** [chef-partners/redhat-subscription-manager-cookbook#36]
https://github.com/chef-partners/redhat-subscription-manager-cookbook/blob/1014cd8c34c4c5926e9849f25aa68850e9bfcc8b/libraries/rhsm_register.rb#L35

The call to verify if node is already subscribed to a system fails if you have a minimal machine and subscription-manager rpm isn't installed. Need a package resource to verify subscription manager is installed first.

**Comment by tas50** [comment]
Thanks as usual. I'll get this copied over into the PR where we're added these resources to Chef 14
