### ISSUE TITLE
Require yum-plugin-security to be installed

### ISSUE THREAD

**Issue by erinn** [chef-partners/redhat-subscription-manager-cookbook#5]
Using vagrant packages provided by Chef, yum-plugin-security is not installed by default thus the rhsm_errata_level (and I assume rhsm_errata) fail due to the command not being found. Any harm in ensuring that the plugin is installed before executing the command?

**Comment by adamleff** [comment]
The `yum-plugin-security` package isn't actually a "real" package - those commands are actually part of yum itself (a `yum install yum-plugin-security` will just cause `yum` to get updated). Latest RHEL6 and 7 versions have a new-enough yum that supports the security commands, and I tested on CentOS 7 and found no issue either. I'm hesitant to add this as-is as it will cause yum to get updated out from underneath the user and Chef itself.

Which vagrant box are you using? Can you provide additional error output showing the issue?

**Comment by erinn** [comment]
Sure,
I am running this against a RHEL-6.7 vagrant box created using packer
from: https://github.com/chef/bento

Here is what I get when my recipe calls for the following:
rhsm_errata_level 'critical'

Begin output of yum update --sec-severity=Critical -y ----
       STDOUT: Loaded plugins: package_upload, product-id,
subscription-manager
       Usage: yum [options] COMMAND

```
   List of Commands:

   check          Check for problems in the rpmdb
   check-update   Check for available package updates
   clean          Remove cached data
   deplist        List a package's dependencies
   distribution-synchronization Synchronize installed packages to
```

the latest available versions

```
   downgrade      downgrade a package
   erase          Remove a package or packages from your system
   groupinfo      Display details about a package group
   groupinstall   Install the packages in a group on your system
   grouplist      List available package groups
   groupremove    Remove the packages in a group from your system
   help           Display a helpful usage message
   history        Display, or use, the transaction history
   info           Display details about a package or group of packages
   install        Install a package or packages on your system
   list           List a package or groups of packages
   load-transaction load a saved transaction from filename
   makecache      Generate the metadata cache
   provides       Find what package provides the given value
   reinstall      reinstall a package
   repolist       Display the configured software repositories
   resolvedep     Determine which package provides the given dependency
   search         Search package details for the given string
   shell          Run an interactive yum shell
   update         Update a package or packages on your system
   upgrade        Update packages taking obsoletes into account
   version        Display a version for the machine and/or available
```

repos.
       STDERR: Command line error: no such option: --sec-severity
       ---- End output of yum update --sec-severity=Critical -y ----
       Ran yum update --sec-severity=Critical -y returned 1
       [2015-12-31T18:40:04+00:00] FATAL:
Chef::Exceptions::ChildConvergeError: Chef run process exited
unsuccessfully (exit code 1)

You get the idea, if my recipe instead installs the yum-plugin-security
on RHEL 6, well, everything works just great. This could also be
approached from the standpoint of having this package installed by the
kickstart that the bento json file uses via packer.

The RHEL-7 box works just fine, no arguments there.

-Erinn

**Comment by adamleff** [comment]
@erinn Thanks for the reply and for opening the issue.

After investigating this further, I'm going to defer on addressing this in the cookbook. Because `yum-plugin-security` really just installs/upgrades `yum`, and since the package `yum` is already installed, Chef will not perform the install with an action of `:install`; it sees that there is a newer candidate version available, but it will not proceed as the package is already installed.

The only way around this is to either specify the exact version of yum required (which requires hard-coding the version or making it an attribute), or to set the action to `:upgrade` (which will cause everyone's yum to get upgraded to the absolute latest each time, something that is out-of-scope for this cookbook).

My recommendation would be to perform the yum / yum-plugin-security upgrade in your wrapper cookbook as you're doing now.

**Comment by erinn** [comment]
Sounds reasonable to me, could you do me one favor though and just add a
note in the README about this?

Thanks,
-Erinn

**Comment by adamleff** [comment]
_Totally_ reasonable! I'll take care of that.

**Comment by adamleff** [comment]
@erinn see #6 - we are indeed going to fix this for RHEL6, so I'm not going to update the README :) I obviously messed up when trying to test this issue on RHEL6 and instead tested on RHEL7. My bad!
