### ISSUE TITLE
Errata Install Doesn't Work On RHEL6

### ISSUE THREAD

**Issue by civik** [chef-partners/redhat-subscription-manager-cookbook#7]
It appears that errata updates don't work properly on RHEL6.  It has to do with the --sec-severity option being added by a optional package in RHEL6. Submitted #6 to fix.

**Comment by civik** [comment]
oops, this is a dupe of issue #5 - After reading #5 however, yum-plugin-security is very much an independant installable package in RHEL6 and this library should ensure it is installed if using the errata install option.

**Comment by adamleff** [comment]
We'll work through this on your PR :)
