### ISSUE TITLE
When registering to Redhat's RHSM with u/p - environment not supported

### ISSUE THREAD

**Issue by thenoid** [chef-partners/redhat-subscription-manager-cookbook#9]
When registering to Redhat's RHSM with u/p - environment not supported.

**Comment by adamleff** [comment]
Can you please provide output showing that this doesn't work, including any errors you receive?

**Comment by adamleff** [comment]
I'm able to duplicate this now - I'll have a fix in shortly.

**Comment by adamleff** [comment]
PR #11 opened

**Comment by adamleff** [comment]
Addressed in PR #11, and version 0.3.1 of the cookbook has been released to the supermarket. Thanks for the report.
